### ISSUE TITLE
Icon names are wrong

### ISSUE THREAD

**Issue by runningman84** [abesto/yed-aws-palettes#1]
I have imported the aws palettes into yed. But the icons aren't named correctly. For example the ELB icon is called "EMR Engine".

**Comment by abesto** [comment]
(Once again, I fail at GitHub and didn't get a notification about this issue being opened)

Thanks for the report! I'm just looking into how to fix this properly.

**Comment by abesto** [comment]
I believe this was fixed in https://github.com/abesto/yed-aws-palettes/commit/35a41f11576784a396cfbb0fe7c8ca113098270a. Feel free to re-open if you experience otherwise.
