### ISSUE TITLE
Missing tooltips

### ISSUE THREAD

**Issue by matthurne** [abesto/yed-aws-palettes#6]
It seems that tooltips are no longer present in the graphml files.

**Comment by abesto** [comment]
Thanks for the report; should be fixed now. The labels look a bit funky, but at least they're there. Will need to put in some string mangling in https://github.com/abesto/yed-aws-palettes/blob/master/generator/transform.py (and find the right place first)

**Comment by abesto** [comment]
Closing this issue. If you encounter the same issue again (or any other, for that matter): the current actively maintained fork of this project is now https://github.com/JustDerb/yed-aws-palettes
