### ISSUE TITLE
AWS - SDKs.graphml not working in yEd 3.17.2

### ISSUE THREAD

**Issue by danmana** [abesto/yed-aws-palettes#7]
The `AWS - SDKs.graphml` palette does not load in yEd 3.17.2. It shows just a crossed red rectangle.
Other palettes from this repo load ok.

![image](https://user-images.githubusercontent.com/498419/33833479-747ae634-de88-11e7-85d3-29bae38d2e7c.png)

**Comment by abesto** [comment]
@danmana #9 should fix this; please verify if it works for you.

**Comment by abesto** [comment]
Closing this issue. If you encounter the same issue again (or any other, for that matter): the current actively maintained fork of this project is now https://github.com/JustDerb/yed-aws-palettes

**Comment by danmana** [comment]
Thanks. Fix confirmed
