### ISSUE TITLE
Looking for Maintainer

### ISSUE THREAD

**Issue by abesto** [abesto/yed-aws-palettes#8]
I haven't been using yED for architecture diagrams for a while, and this project has suffered as a result – there's currently at least one bug report that I probably won't get around to investigating. This project is now “officially” unsupported, and is looking for a new, loving maintainer.

**Comment by JustDerb** [comment]
I'd be able to take on this project to help maintain it. I have a lot of ideas on how to possibly auto-update it (without conflicting with yED's licensing)...

**Comment by abesto** [comment]
@JustDerb , that's great news. Based on your previous contributions, I'm happy to hand the project off to you. I've just sent you an invitation to be a "collaborator" on the repo. Do you know how stuff like this is usually handled? Is it preferred to reassign the repo to you as the new owner instead?

**Comment by JustDerb** [comment]
Thanks. Accepted.

> Do you know how stuff like this is usually handled? Is it preferred to reassign the repo to you as the new owner instead?

Generally, you just update the README.md to point to a new forked repo :P

But, if you *really* want to transfer it, you can follow: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by abesto** [comment]
Right, that makes sense. To keep things clean (“things” being mostly GH issues), I'll open the request to transfer the repo to you.

Thank you once again for taking on this!

**Comment by abesto** [comment]
... I mean, I would, except the target repo already exists (obviously). Guess I'll just update the README and open issues then.
